#!/bin/bash

killall -s USR2 iptraf
iptraf -i all -f -B -L /home/cyberstorm/cyberstorm/realtime-backend/bandwidth/logfile.txt
#sudo chmod a+rw logfile.txt
echo !!!
while [ 1 ]
do
	perl first.pl < logfile.txt > bandwidth.txt
	python StatsDB.py 
	echo "" > logfile.txt
	sleep 5
done
